/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AUTH_API_URL": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "AWS_SES_ACCESS_KEY_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AWS_SES_SECRET_ACCESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Api": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "AuthApi": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "AuthStorage": {
      "type": "sst.cloudflare.Kv"
    }
    "Bucket": {
      "name": string
      "type": "sst.cloudflare.Bucket"
    }
    "Console": {
      "type": "sst.cloudflare.SolidStart"
      "url": string
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.sst.Linkable"
      "username": string
    }
    "Desktop": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
    "EMAILOCTOPUS_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_APP_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_ID_CONSOLE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_SECRET_CONSOLE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HONEYCOMB_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LogProcessor": {
      "type": "sst.cloudflare.Worker"
    }
    "STRIPE_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_WEBHOOK_SECRET": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "Web": {
      "type": "sst.cloudflare.Astro"
      "url": string
    }
    "ZEN_MODELS": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}